// Automatically parsed dataset from user context
const MEDICAL_DATASET = [
  {
    "disease": "hypertensive disease",
    "specialists": [
      "Cardiologist"
    ],
    "symptoms": [
      "pain chest",
      "shortness of breath",
      "dizziness",
      "asthenia",
      "fall",
      "syncope",
      "vertigo",
      "sweat",
      "sweating increased",
      "palpitation",
      "nausea",
      "angina pectoris",
      "pressure chest"
    ]
  },
  {
    "disease": "diabetes",
    "specialists": [
      "Endocrinologist",
      "Family Physician",
      "Optometrist",
      "Interventional Cardiologist",
      "General Surgeon",
      "Internist",
      "Transplant Surgeon",
      "Metabolic Surgeon",
      "Psychologist",
      "Pediatric Endocrinologist"
    ],
    "symptoms": [
      "polyuria",
      "polydypsia",
      "shortness of breath",
      "pain chest",
      "asthenia",
      "nausea",
      "orthopnea",
      "rale",
      "sweat",
      "sweating increased",
      "unresponsiveness",
      "mental status changes",
      "vertigo",
      "vomiting",
      "labored breathing",
      "weight gain",
      "thirst",
      "symptoms of the kidneys",
      "increased thirst",
      "frequent urination",
      "extreme hunger",
      "unexplained weight loss",
      "presence of ketones in the urine (ketones are a byproduct of the breakdown of muscle and fat that happens when there's not enough available insulin)",
      "fatigue",
      "irritability",
      "blurred vision",
      "slow-healing sores",
      "frequent infections, such as gums or skin infections and vaginal infections"
    ]
  },
  {
    "disease": "depression mental",
    "specialists": [
      "Psychiatrist",
      "Psychologist"
    ],
    "symptoms": [
      "feeling suicidal",
      "suicidal",
      "hallucinations auditory",
      "feeling hopeless",
      "weepiness",
      "sleeplessness",
      "motor retardation",
      "irritable mood",
      "blackout",
      "mood depressed",
      "hallucinations visual",
      "worry",
      "agitation",
      "tremor",
      "intoxication",
      "verbal auditory hallucinations",
      "energy increased",
      "difficulty",
      "nightmare",
      "unable to concentrate",
      "homelessness"
    ]
  },
  {
    "disease": "coronary heart disease",
    "specialists": [
      "Cardiologist"
    ],
    "symptoms": [
      "pain chest",
      "angina pectoris",
      "shortness of breath",
      "hypokinesia",
      "sweat",
      "sweating increased",
      "pressure chest",
      "dyspnea on exertion",
      "orthopnea",
      "chest tightness"
    ]
  },
  {
    "disease": "pneumonia",
    "specialists": [
      "Pulmonologist",
      "Respirologist",
      "Pediatric Infectious Disease Specialist",
      "Internist",
      "Hospitalist"
    ],
    "symptoms": [
      "cough",
      "fever",
      "decreased translucency",
      "shortness of breath",
      "rale",
      "productive cough",
      "pleuritic pain",
      "yellow sputum",
      "breath sounds decreased",
      "chill",
      "rhonchus",
      "green sputum",
      "non-productive cough",
      "wheezing",
      "haemoptysis",
      "distress respiratory",
      "tachypnea",
      "malaise",
      "night sweat",
      "sharp chest pain",
      "nasal congestion",
      "difficulty breathing",
      "vomiting",
      "weakness",
      "sore throat",
      "coryza",
      "chills",
      "fatigue",
      "high fever",
      "breathlessness",
      "sweating",
      "chest pain",
      "fast heart rate",
      "rusty sputum",
      "phlegm",
      "chest pain when you breathe or cough",
      "confusion or changes in mental awareness (in adults age 65 and older)",
      "cough, which may produce phlegm",
      "fever, sweating and shaking chills",
      "lower than normal body temperature (in adults older than age 65 and people with weak immune systems)",
      "nausea, vomiting or diarrhea",
      "adults older than age 65",
      "children younger than age 2 with signs and symptoms",
      "people with an underlying health condition or weakened immune system",
      "people receiving chemotherapy or taking medication that suppresses the immune system"
    ]
  },
  {
    "disease": "asthma",
    "specialists": [
      "Clinical Immunologist",
      "Allergist",
      "Allergist-Immunologist",
      "Pulmonologist",
      "Pediatrician",
      "Internist",
      "Hospitalist"
    ],
    "symptoms": [
      "wheezing",
      "cough",
      "shortness of breath",
      "chest tightness",
      "non-productive cough",
      "pleuritic pain",
      "productive cough",
      "symptom aggravating factors",
      "distress respiratory",
      "difficulty breathing",
      "nasal congestion",
      "fever",
      "sharp chest pain",
      "coryza",
      "allergic reaction",
      "coughing up sputum",
      "congestion in chest",
      "chest tightness or pain",
      "wheezing when exhaling, which is a common sign of asthma in children",
      "trouble sleeping caused by shortness of breath, coughing or wheezing",
      "coughing or wheezing attacks that are worsened by a respiratory virus, such as a cold or the flu",
      "asthma signs and symptoms that are more frequent and bothersome",
      "increasing difficulty breathing, as measured with a device used to check how well your lungs are working (peak flow meter)",
      "the need to use a quick-relief inhaler more often",
      "exercise-induced asthma, which may be worse when the air is cold and dry",
      "occupational asthma, triggered by workplace irritants such as chemical fumes, gases or dust",
      "allergy-induced asthma, triggered by airborne substances, such as pollen, mold spores, cockroach waste, or particles of skin and dried saliva shed by pets (pet dander)"
    ]
  },
  {
    "disease": "myocardial infarction",
    "specialists": [
      "Cardiologist"
    ],
    "symptoms": [
      "pain chest",
      "st segment elevation",
      "sweat",
      "sweating increased",
      "shortness of breath",
      "st segment depression",
      "hypokinesia",
      "angina pectoris",
      "pressure chest",
      "t wave inverted",
      "orthopnea",
      "rale",
      "chest tightness",
      "presence of q wave",
      "palpitation",
      "dyspnea",
      "chest discomfort",
      "bradycardia",
      "syncope"
    ]
  },
  {
    "disease": "anemia",
    "specialists": [
      "Hematologist",
      "Hematologist / Oncologist",
      "Pediatric Hematologist / Oncologist",
      "Pediatric Psychologist",
      "Gastroenterologist"
    ],
    "symptoms": [
      "chill",
      "guaiac positive",
      "monoclonal",
      "ecchymosis",
      "tumor cell invasion",
      "haemorrhage",
      "pallor",
      "asthenia",
      "fatigue",
      "heme positive",
      "pain back",
      "orthostasis",
      "hyponatremia",
      "dizziness",
      "shortness of breath",
      "pain",
      "rhonchus",
      "arthralgia",
      "swelling",
      "transaminitis",
      "weakness",
      "nosebleed",
      "heavy menstrual flow",
      "melena",
      "unpredictable menstruation",
      "vomiting blood",
      "changes in stool appearance",
      "recent pregnancy",
      "too little hair",
      "pale or yellowish skin",
      "irregular heartbeats",
      "dizziness or lightheadedness",
      "chest pain",
      "cold hands and feet",
      "headaches"
    ]
  },
  {
    "disease": "dementia",
    "specialists": [
      "Neurologist"
    ],
    "symptoms": [
      "fever",
      "fall",
      "unresponsiveness",
      "lethargy",
      "agitation",
      "ecchymosis",
      "syncope",
      "rale",
      "unconscious state",
      "cough",
      "bedridden",
      "pain",
      "facial paresis",
      "abdominal tenderness",
      "rhonchus",
      "unsteady gait",
      "hallucinations auditory",
      "disturbance of memory",
      "problems with movement",
      "dizziness",
      "depressive or psychotic symptoms",
      "abnormal involuntary movements",
      "paresthesia",
      "hostile behavior",
      "delusions or hallucinations",
      "difficulty speaking",
      "insomnia",
      "disturbance of smell or taste",
      "focal weakness",
      "memory loss and confusion",
      "poor judgement",
      "diffculty speaking",
      "repeating questions"
    ]
  },
  {
    "disease": "hypothyroidism",
    "specialists": [
      "Endocrinologist"
    ],
    "symptoms": [
      "shortness of breath",
      "prostatism",
      "drowsiness",
      "sleepy",
      "hyponatremia",
      "fall",
      "unsteady gait",
      "polyuria",
      "hypotension",
      "difficulty",
      "syncope",
      "nightmare",
      "speech slurred",
      "weight gain",
      "asthenia",
      "fatigue",
      "tired",
      "agitation",
      "mental status changes",
      "motor retardation",
      "vomiting",
      "numbness",
      "mass of body structure",
      "too little hair",
      "muscle pain",
      "hot flashes",
      "leg cramps or spasms",
      "absence of menstruation",
      "poor circulation",
      "wrist swelling",
      "feeling cold",
      "thirst",
      "cold hands and feets",
      "mood swings",
      "lethargy",
      "dizziness",
      "puffy face and eyes",
      "enlarged thyroid",
      "brittle nails",
      "swollen extremeties",
      "depression",
      "irritability",
      "abnormal menstruation",
      "increased sensitivity to cold",
      "constipation",
      "dry skin",
      "puffy face",
      "hoarseness",
      "muscle weakness",
      "elevated blood cholesterol level",
      "muscle aches, tenderness and stiffness",
      "pain, stiffness or swelling in your joints",
      "heavier than normal or irregular menstrual periods",
      "thinning hair",
      "slowed heart rate",
      "impaired memory",
      "enlarged thyroid gland (goiter)"
    ]
  },
  {
    "disease": "gerd",
    "specialists": [
      "Gastroenterologist",
      "General Surgeon",
      "Internist",
      "Family Physician",
      "Thoracic Surgeon",
      "Pediatric Surgeon"
    ],
    "symptoms": [
      "stomach pain",
      "acidity",
      "ulcers on tongue",
      "vomiting",
      "cough",
      "chest pain",
      "a burning sensation in your chest (heartburn), usually after eating, which might be worse at night",
      "difficulty swallowing",
      "regurgitation of food or sour liquid",
      "sensation of a lump in your throat",
      "chronic cough",
      "laryngitis",
      "new or worsening asthma",
      "disrupted sleep"
    ]
  },
  {
    "disease": "stroke",
    "specialists": [
      "Neurologist",
      "Neurosurgeon",
      "Emergency Medicine Physician",
      "Physiatrist",
      "Pediatric Hematologist / Oncologist",
      "Interventional Cardiologist"
    ],
    "symptoms": [
      "focal weakness",
      "dizziness",
      "headache",
      "loss of sensation",
      "weakness",
      "problems with movement",
      "slurring words",
      "difficulty speaking",
      "depressive or psychotic symptoms",
      "seizures",
      "abnormal involuntary movements",
      "disturbance of memory",
      "trouble speaking and understanding what others are saying - you may experience confusion, slur words or have difficulty understanding speech",
      "paralysis or numbness of the face, arm or leg - you may develop sudden numbness, weakness or paralysis in the face, arm or leg; this often affects just one side of the body; try to raise both your arms over your head at the same time; if one arm begins to fall, you may be having a stroke; also, one side of your mouth may droop when you try to smile",
      "problems seeing in one or both eyes - you may suddenly have blurred or blackened vision in one or both eyes, or you may see double",
      "headache - a sudden, severe headache, which may be accompanied by vomiting, dizziness or altered consciousness, may indicate that you're having a stroke",
      "trouble walking - you may stumble or lose your balance; you may also have sudden dizziness or a loss of coordination"
    ]
  },
  {
    "disease": "migraine",
    "specialists": [
      "Neurologist"
    ],
    "symptoms": [
      "headache",
      "nausea",
      "vomiting",
      "dizziness",
      "diminished vision",
      "disturbance of memory",
      "spots or clouds in vision",
      "symptoms of the face",
      "blindness",
      "long menstrual periods",
      "acidity",
      "indigestion",
      "blurred and distorted vision",
      "excessive hunger",
      "stiff neck",
      "depression",
      "irritability",
      "visual disturbances",
      "glossary"
    ]
  },
  {
    "disease": "appendicitis",
    "specialists": [
      "General Surgeon"
    ],
    "symptoms": [
      "sharp abdominal pain",
      "lower abdominal pain",
      "vomiting",
      "nausea",
      "fever",
      "burning abdominal pain",
      "side pain",
      "diarrhea",
      "upper abdominal pain",
      "chills",
      "decreased appetite",
      "stomach bloating",
      "sudden pain that begins on the right side of the lower abdomen",
      "sudden pain that begins around your navel and often shifts to your lower right abdomen",
      "pain that worsens if you cough, walk or make other jarring movements",
      "nausea and vomiting",
      "loss of appetite",
      "low-grade fever that may worsen as the illness progresses",
      "constipation or diarrhea",
      "abdominal bloating",
      "flatulence"
    ]
  },
  {
    "disease": "kidney stone",
    "specialists": [
      "Urologist",
      "Nephrologist"
    ],
    "symptoms": [
      "side pain",
      "sharp abdominal pain",
      "back pain",
      "vomiting",
      "nausea",
      "blood in urine",
      "lower abdominal pain",
      "low back pain",
      "painful urination",
      "frequent urination",
      "retention of urine",
      "suprapubic pain"
    ]
  },
  {
    "disease": "hyperthyroidism",
    "specialists": [
      "Urologist",
      "Endocrinologist",
      "Endocrine Surgeon",
      "Radiologist",
      "Family Physician",
      "Public Health and General Preventive Medicine Specialist"
    ],
    "symptoms": [
      "fatigue",
      "mood swings",
      "weight loss",
      "restlessness",
      "sweating",
      "diarrhoea",
      "fast heart rate",
      "excessive hunger",
      "muscle weakness",
      "irritability",
      "abnormal menstruation",
      "unintentional weight loss, even when your appetite and food intake stay the same or increase",
      "rapid heartbeat (tachycardia) - commonly more than 100 beats a minute",
      "irregular heartbeat (arrhythmia)",
      "pounding of your heart (palpitations)",
      "increased appetite",
      "nervousness, anxiety and irritability",
      "tremor - usually a fine trembling in your hands and fingers",
      "changes in menstrual patterns",
      "increased sensitivity to heat",
      "changes in bowel patterns, especially more frequent bowel movements",
      "an enlarged thyroid gland (goiter), which may appear as a swelling at the base of your neck",
      "fatigue, muscle weakness",
      "difficulty sleeping",
      "skin thinning",
      "fine, brittle hair"
    ]
  },
  {
    "disease": "osteoarthritis",
    "specialists": [
      "Rheumatologist",
      "Primary Care Physician",
      "Orthopedic Surgeon",
      "PM&R Physician",
      "Physiatrist",
      "Sports Medicine Specialist",
      "Neurologist",
      "Radiologist",
      "Plastic Surgeon",
      "Hand Surgeon"
    ],
    "symptoms": [
      "knee pain",
      "hip pain",
      "shoulder pain",
      "back pain",
      "leg pain",
      "hand or finger pain",
      "joint pain",
      "knee swelling",
      "ankle pain",
      "elbow pain",
      "muscle pain",
      "knee weakness",
      "pain - affected joints might hurt during or after movement",
      "stiffness - joint stiffness might be most noticeable upon awakening or after being inactive",
      "tenderness - your joint might feel tender when you apply light pressure to or near it",
      "loss of flexibility - you might not be able to move your joint through its full range of motion",
      "grating sensation - you might feel a grating sensation when you use the joint, and you might hear popping or crackling",
      "bone spurs - these extra bits of bone, which feel like hard lumps, can form around the affected joint",
      "swelling - this might be caused by soft tissue inflammation around the joint"
    ]
  },
  {
    "disease": "rheumatoid arthritis",
    "specialists": [
      "Rheumatologist",
      "Orthopedic Surgeon",
      "Oral and Maxillofacial Surgeon",
      "Hand Surgeon"
    ],
    "symptoms": [
      "joint pain",
      "knee pain",
      "ache all over",
      "hand or finger pain",
      "wrist pain",
      "peripheral edema",
      "hand or finger swelling",
      "joint swelling",
      "hand or finger weakness",
      "elbow swelling",
      "wrist swelling",
      "stiffness all over",
      "tender, warm, swollen joints",
      "joint stiffness that is usually worse in the mornings and after inactivity",
      "fatigue, fever and loss of appetite",
      "skin",
      "eyes",
      "lungs",
      "heart",
      "kidneys",
      "salivary glands",
      "nerve tissue",
      "bone marrow",
      "blood vessels"
    ]
  },
  {
    "disease": "tuberculosis",
    "specialists": [
      "Infectious Disease Specialist",
      "Critical Care Specialist",
      "Pulmonologist",
      "Sleep Medicine Specialist"
    ],
    "symptoms": [
      "cough",
      "shortness of breath",
      "sweating",
      "congestion in chest",
      "hemoptysis",
      "skin dryness",
      "peeling",
      "scaliness",
      "or roughness",
      "drainage in throat",
      "hurts to breath",
      "itchiness of eye",
      "back cramps or spasms",
      "vaginal itching",
      "chills",
      "vomiting",
      "fatigue",
      "weight loss",
      "high fever",
      "breathlessness",
      "loss of appetite",
      "mild fever",
      "yellowing of eyes",
      "swelled lymph nodes",
      "malaise",
      "phlegm",
      "chest pain",
      "blood in sputum",
      "latent tuberculosis(tb) - you have a tuberculosis(tb) infection, but the bacteria in your body are inactive and cause no symptoms; latent tuberculosis(tb), also called inactive tuberculosis(tb) or tuberculosis(tb) infection, isn't contagious; latent tuberculosis(tb) can turn into active tuberculosis(tb), so treatment is important",
      "active tuberculosis(tb) - also called tuberculosis(tb) disease, this condition makes you sick and, in most cases, can spread to others; it can occur weeks or years after infection with the tuberculosis(tb) bacteria",
      "coughing for three or more weeks",
      "coughing up blood or mucus",
      "chest pain, or pain with breathing or coughing",
      "unintentional weight loss",
      "fever",
      "night sweats"
    ]
  },
  {
    "disease": "pancreatitis",
    "specialists": [
      "Gastroenterologist",
      "Hepatobiliary and Pancreas Surgeon",
      "General Surgeon",
      "Critical Care Specialist"
    ],
    "symptoms": [
      "vomiting",
      "pain abdominal",
      "nausea",
      "pain",
      "diarrhea",
      "stool color yellow",
      "rigor - temperature-associated observation",
      "apyrexial",
      "sore to touch",
      "upper abdominal pain",
      "abdominal pain that radiates to your back",
      "tenderness when touching the abdomen",
      "fever",
      "rapid pulse",
      "abdominal pain that feels worse after eating",
      "losing weight without trying",
      "oily, smelly stools (steatorrhea)"
    ]
  },
  {
    "disease": "urinary tract infection",
    "specialists": [
      "Urologist",
      "Pediatric Nephrologist",
      "Pediatric Infectious Disease Specialist",
      "Family Physician",
      "Infectious Disease Specialist"
    ],
    "symptoms": [
      "painful urination",
      "suprapubic pain",
      "sharp abdominal pain",
      "frequent urination",
      "fever",
      "vomiting",
      "back pain",
      "nausea",
      "blood in urine",
      "side pain",
      "retention of urine",
      "lower abdominal pain",
      "burning micturition",
      "bladder discomfort",
      "foul smell of urine",
      "continuous feel of urine",
      "a strong, persistent urge to urinate",
      "a burning sensation when urinating",
      "passing frequent, small amounts of urine",
      "urine that appears cloudy",
      "urine that appears red, bright pink or cola-colored - a sign of blood in the urine",
      "strong-smelling urine",
      "pelvic pain, in women - especially in the center of the pelvis and around the area of the pubic bone"
    ]
  },
  {
    "disease": "gout",
    "specialists": [
      "Rheumatologist",
      "Hospitalist",
      "Family Physician",
      "Bariatrician"
    ],
    "symptoms": [
      "hot flush",
      "pain",
      "redness",
      "swelling",
      "erythema",
      "emphysematous change",
      "sore to touch",
      "hypokinesia",
      "ascites",
      "patient non compliance",
      "foot or toe pain",
      "knee pain",
      "foot or toe swelling",
      "ankle pain",
      "wrist pain",
      "hand or finger pain",
      "hand or finger swelling",
      "joint pain",
      "ankle swelling",
      "knee swelling",
      "leg swelling",
      "wrist swelling",
      "intense joint pain - gout usually affects the big toe, but it can occur in any joint; other commonly affected joints include the ankles, knees, elbows, wrists and fingers; the pain is likely to be most severe within the first four to 12 hours after it begins",
      "lingering discomfort - after the most severe pain subsides, some joint discomfort may last from a few days to a few weeks; later attacks are likely to last longer and affect more joints",
      "inflammation and redness - the affected joint or joints become swollen, tender, warm and red",
      "limited range of motion - as gout progresses, you may not be able to move your joints normally"
    ]
  },
  {
    "disease": "irritable bowel syndrome",
    "specialists": [
      "Gastroenterologist",
      "Pediatric Surgeon"
    ],
    "symptoms": [
      "sharp abdominal pain",
      "diarrhea",
      "burning abdominal pain",
      "constipation",
      "nausea",
      "anxiety and nervousness",
      "lower abdominal pain",
      "upper abdominal pain",
      "regurgitation",
      "insomnia",
      "rectal bleeding",
      "flatulence",
      "abdominal pain, cramping or bloating that is related to passing a bowel movement",
      "changes in appearance of bowel movement",
      "changes in how often you are having a bowel movement"
    ]
  },
  {
    "disease": "psoriasis",
    "specialists": [
      "Dermatologist"
    ],
    "symptoms": [
      "skin rash",
      "itching of skin",
      "skin dryness",
      "peeling",
      "scaliness",
      "or roughness",
      "skin lesion",
      "abnormal appearing skin",
      "itchy scalp",
      "irregular appearing scalp",
      "joint pain",
      "skin moles",
      "skin growth",
      "skin swelling",
      "acne or pimples",
      "skin peeling",
      "silver like dusting",
      "small dents in nails",
      "inflammatory nails",
      "red patches of skin covered with thick, silvery scales",
      "small scaling spots (commonly seen in children)",
      "dry, cracked skin that may bleed or itch",
      "itching, burning or soreness",
      "thickened, pitted or ridged nails",
      "swollen and stiff joints"
    ]
  },
  {
    "disease": "alzheimer's disease",
    "specialists": [
      "Neurologist"
    ],
    "symptoms": [
      "drool",
      "agitation",
      "nightmare",
      "rhonchus",
      "consciousness clear",
      "pin-point pupils",
      "bedridden",
      "frail",
      "tremor resting",
      "hyperkalemia",
      "facial paresis",
      "groggy",
      "muscle twitch",
      "wheelchair bound",
      "tremor",
      "cough",
      "fever"
    ]
  },
  {
    "disease": "fibromyalgia",
    "specialists": [
      "Rheumatologist",
      "Internist"
    ],
    "symptoms": [
      "back pain",
      "ache all over",
      "neck pain",
      "muscle pain",
      "leg pain",
      "headache",
      "shoulder pain",
      "low back pain",
      "sharp chest pain",
      "arm pain",
      "hip pain",
      "fatigue",
      "widespread pain - the pain associated with fibromyalgia often is described as a constant dull ache that has lasted for at least three months; to be considered widespread, the pain must occur on both sides of your body and above and below your waist",
      "fatigue - people with fibromyalgia often awaken tired, even though they report sleeping for long periods of time; sleep is often disrupted by pain, and many patients with fibromyalgia have other sleep disorders, such as restless legs syndrome and sleep apnea",
      "cognitive difficulties - a symptom commonly referred to as \"fibro fog\" impairs the ability to focus, pay attention and concentrate on mental tasks",
      "irritable bowel syndrome",
      "chronic fatigue syndrome",
      "migraine and other types of headaches",
      "interstitial cystitis or painful bladder syndrome",
      "temporomandibular joint disorders",
      "anxiety",
      "depression",
      "postural tachycardia syndrome"
    ]
  },
  {
    "disease": "celiac disease",
    "specialists": [
      "Gastroenterologist",
      "Pediatric Gastroenterologist",
      "Pediatrician",
      "Internist"
    ],
    "symptoms": [
      "sharp abdominal pain",
      "diarrhea",
      "regurgitation",
      "fatigue",
      "vomiting",
      "nausea",
      "allergic reaction",
      "sharp chest pain",
      "fears and phobias",
      "peripheral edema",
      "leg lump or mass",
      "constipation",
      "weight loss",
      "bloating and gas",
      "abdominal pain",
      "nausea and vomiting",
      "anemia, usually from iron deficiency",
      "loss of bone density (osteoporosis) or softening of bone (osteomalacia)",
      "itchy, blistery skin rash (dermatitis herpetiformis)",
      "mouth ulcers",
      "headaches and fatigue",
      "nervous system injury, including numbness and tingling in the feet and hands, possible problems with balance, and cognitive impairment",
      "joint pain",
      "reduced functioning of the spleen (hyposplenism)"
    ]
  },
  {
    "disease": "atrial fibrillation",
    "specialists": [
      "Cardiologist",
      "Cardiothoracic Surgeon",
      "Cardiac Electrophysiologist",
      "Cardiovascular Surgeon",
      "Neurologist",
      "Interventional Cardiologist"
    ],
    "symptoms": [
      "shortness of breath",
      "sharp chest pain",
      "palpitations",
      "dizziness",
      "irregular heartbeat",
      "fatigue",
      "increased heart rate",
      "decreased heart rate",
      "sensations of a fast, fluttering or pounding heartbeat (palpitations)",
      "chest pain",
      "lightheadedness",
      "reduced ability to exercise",
      "weakness"
    ]
  },
  {
    "disease": "epilepsy",
    "specialists": [
      "Neurologist",
      "Neurosurgeon",
      "Psychologist",
      "Radiologist"
    ],
    "symptoms": [
      "seizure",
      "hypometabolism",
      "aura",
      "muscle twitch",
      "drowsiness",
      "tremor",
      "unresponsiveness",
      "hemiplegia",
      "myoclonus",
      "gurgle",
      "sleepy",
      "lethargy",
      "wheelchair bound",
      "seizures",
      "headache",
      "abnormal involuntary movements",
      "disturbance of memory",
      "difficulty speaking",
      "lack of growth",
      "stiffness all over",
      "eye moves abnormally",
      "muscle weakness",
      "temporary confusion",
      "a staring spell",
      "stiff muscles",
      "uncontrollable jerking movements of the arms and legs",
      "loss of consciousness or awareness",
      "psychological symptoms such as fear, anxiety or deja vu"
    ]
  },
  {
    "disease": "multiple sclerosis",
    "specialists": [
      "Neurologist",
      "Physiatrist",
      "Psychologist",
      "Neuropsychologist",
      "Pediatric Urologist"
    ],
    "symptoms": [
      "fatigue",
      "loss of sensation",
      "headache",
      "dizziness",
      "problems with movement",
      "weakness",
      "leg weakness",
      "paresthesia",
      "disturbance of memory",
      "abnormal involuntary movements",
      "leg stiffness or tightness",
      "focal weakness",
      "numbness or weakness in one or more limbs that typically occurs on one side of your body at a time, or your legs and trunk",
      "electric-shock sensations that occur with certain neck movements, especially bending the neck forward (lhermitte sign)",
      "tremor, lack of coordination or unsteady gait",
      "partial or complete loss of vision, usually in one eye at a time, often with pain during eye movement",
      "prolonged double vision",
      "blurry vision",
      "slurred speech",
      "tingling or pain in parts of your body",
      "problems with sexual, bowel and bladder function"
    ]
  },
  {
    "disease": "crohn disease",
    "specialists": [
      "Gastroenterologist"
    ],
    "symptoms": [
      "sharp abdominal pain",
      "diarrhea",
      "vomiting",
      "nausea",
      "burning abdominal pain",
      "blood in stool",
      "rectal bleeding",
      "pain of the anus",
      "joint pain",
      "stomach bloating",
      "heartburn",
      "regurgitation"
    ]
  },
  {
    "disease": "lupus",
    "specialists": [
      "Pediatric Rheumatologist",
      "Rheumatologist",
      "Dermatologist"
    ],
    "symptoms": [
      "fatigue",
      "fever",
      "joint pain, stiffness and swelling",
      "butterfly-shaped rash on the face that covers the cheeks and bridge of the nose or rashes elsewhere on the body",
      "skin lesions that appear or worsen with sun exposure",
      "fingers and toes that turn white or blue when exposed to cold or during stressful periods",
      "shortness of breath",
      "chest pain",
      "dry eyes",
      "headaches, confusion and memory loss"
    ]
  },
  {
    "disease": "endometriosis",
    "specialists": [
      "Obstetrician",
      "Gynecologist",
      "Gynecologic Oncologist"
    ],
    "symptoms": [
      "pelvic pain",
      "sharp abdominal pain",
      "lower abdominal pain",
      "painful menstruation",
      "heavy menstrual flow",
      "burning abdominal pain",
      "infertility",
      "intermenstrual bleeding",
      "hot flashes",
      "absence of menstruation",
      "vaginal pain",
      "chills",
      "painful periods (dysmenorrhea) - pelvic pain and cramping may begin before and extend several days into a menstrual period; you may also have lower back and abdominal pain",
      "pain with intercourse - pain during or after sex is common with endometriosis",
      "pain with bowel movements or urination - you're most likely to experience these symptoms during a menstrual period",
      "excessive bleeding - you may experience occasional heavy menstrual periods or bleeding between periods (intermenstrual bleeding)",
      "infertility - sometimes, endometriosis is first diagnosed in those seeking treatment for infertility",
      "other signs and symptoms - you may experience fatigue, diarrhea, constipation, bloating or nausea, especially during menstrual periods"
    ]
  },
  {
    "disease": "pcos",
    "specialists": [
      "Endocrinologist",
      "Gynecologist"
    ],
    "symptoms": [
      "infertility",
      "unpredictable menstruation",
      "weight gain",
      "pelvic pain",
      "absence of menstruation",
      "heavy menstrual flow",
      "intermenstrual bleeding",
      "long menstrual periods",
      "painful menstruation",
      "cramps and spasms",
      "hot flashes",
      "acne or pimples"
    ]
  },
  {
    "disease": "carpal tunnel syndrome",
    "specialists": [
      "Physiatrist",
      "Orthopedic Surgeon",
      "Neurosurgeon",
      "Sports Medicine Specialist",
      "Hand Surgeon"
    ],
    "symptoms": [
      "loss of sensation",
      "hand or finger pain",
      "wrist pain",
      "paresthesia",
      "arm pain",
      "neck pain",
      "hand or finger weakness",
      "elbow pain",
      "hand or finger stiffness or tightness",
      "hand or finger swelling",
      "arm weakness",
      "wrist swelling",
      "tingling or numbness - you may notice tingling and numbness in the fingers or hand; usually the thumb and index, middle or ring fingers are affected, but not the little finger; you might feel a sensation like an electric shock in these fingersthe sensation may travel from the wrist up the arm; these symptoms often occur while holding a steering wheel, phone or newspaper, or may wake you from sleepmany people \"shake out\" their hands to try to relieve their symptoms; the numb feeling may become constant over time",
      "weakness - you may experience weakness in the hand and drop objects; this may be due to the numbness in the hand or weakness of the thumb's pinching muscles, which are also controlled by the median nerve"
    ]
  },
  {
    "disease": "shingles",
    "specialists": [
      "Primary Care Physician",
      "Dermatologist"
    ],
    "symptoms": [
      "pain, burning, numbness or tingling",
      "sensitivity to touch",
      "a red rash that begins a few days after the pain",
      "fluid-filled blisters that break open and crust over",
      "itching",
      "fever",
      "headache",
      "sensitivity to light",
      "fatigue"
    ]
  },
  {
    "disease": "lyme disease",
    "specialists": [
      "Rheumatologist",
      "Infectious Disease Specialist"
    ],
    "symptoms": [
      "fever",
      "skin rash",
      "headache",
      "fatigue",
      "abnormal appearing skin",
      "loss of sensation",
      "depressive or psychotic symptoms",
      "joint pain",
      "chills",
      "hip pain",
      "hand or finger pain",
      "symptoms of the face",
      "flat, circular rash anywhere on your body",
      "joint pain and swelling",
      "muscle aches"
    ]
  },
  {
    "disease": "iron deficiency anemia",
    "specialists": [
      "Hematologist"
    ],
    "symptoms": [
      "fatigue",
      "weakness",
      "dizziness",
      "heavy menstrual flow",
      "rectal bleeding",
      "blood in stool",
      "weight gain",
      "melena",
      "heartburn",
      "regurgitation",
      "intermenstrual bleeding",
      "absence of menstruation",
      "extreme fatigue",
      "pale skin",
      "chest pain, fast heartbeat or shortness of breath",
      "headache, dizziness or lightheadedness",
      "cold hands and feet",
      "inflammation or soreness of your tongue",
      "brittle nails",
      "unusual cravings for non-nutritive substances, such as ice, dirt or starch",
      "poor appetite, especially in infants and children with iron deficiency anemia"
    ]
  },
  {
    "disease": "concussion",
    "specialists": [
      "Family Physician",
      "General Practitioner",
      "PM&R Physician",
      "Physiatrist",
      "Sports Medicine Specialist",
      "Pediatric Physiatrist",
      "Neurologist",
      "Psychologist",
      "Pediatric Sports Medicine Specialist",
      "Pediatrician"
    ],
    "symptoms": [
      "headache",
      "dizziness",
      "neck pain",
      "vomiting",
      "disturbance of memory",
      "nausea",
      "back pain",
      "facial pain",
      "sleepiness",
      "rib pain",
      "double vision",
      "difficulty speaking",
      "ringing in the ears",
      "fatigue or drowsiness",
      "blurry vision",
      "confusion or feeling as if in a fog",
      "amnesia surrounding the traumatic event",
      "dizziness or \"seeing stars\"",
      "temporary loss of consciousness (though this doesn't always occur)",
      "slurred speech",
      "delayed response to questions",
      "dazed appearance",
      "forgetfulness, such as repeatedly asking the same question",
      "concentration and memory complaints",
      "irritability and other personality changes",
      "sensitivity to light and noise",
      "sleep disturbances",
      "psychological adjustment problems and depression",
      "disorders of taste and smell"
    ]
  },
  {
    "disease": "dengue fever",
    "specialists": [
      "Medical Microbiologist",
      "Infectious Disease Doctor",
      "Primary Care Physician",
      "Infectious Disease Specialist"
    ],
    "symptoms": [
      "sore throat",
      "fever",
      "shoulder cramps or spasms",
      "ankle pain",
      "wrist pain",
      "pain during pregnancy",
      "joint stiffness or tightness",
      "excessive anger",
      "pain or soreness of breast",
      "knee lump or mass",
      "facial pain",
      "pain in eye",
      "headache",
      "muscle, bone or joint pain",
      "nausea",
      "vomiting",
      "pain behind the eyes",
      "swollen glands",
      "rash",
      "severe stomach pain",
      "persistent vomiting",
      "bleeding from your gums or nose",
      "blood in your urine, stools or vomit",
      "bleeding under the skin, which might look like bruising",
      "difficult or rapid breathing",
      "fatigue",
      "irritability or restlessness"
    ]
  },
  {
    "disease": "malaria",
    "specialists": [
      "Internist",
      "Infectious Disease Specialist",
      "Emergency Medicine Specialist",
      "Primary Care Physician",
      "Medical Microbiologist"
    ],
    "symptoms": [
      "headache",
      "fever",
      "ache all over",
      "weakness",
      "vomiting",
      "back pain",
      "fainting",
      "vulvar sore",
      "excessive growth",
      "knee lump or mass",
      "itchy eyelid",
      "wrist weakness",
      "chills",
      "high fever",
      "sweating",
      "nausea",
      "muscle pain",
      "diarrhoea",
      "general feeling of discomfort",
      "nausea and vomiting",
      "diarrhea",
      "abdominal pain",
      "muscle or joint pain",
      "fatigue",
      "rapid breathing",
      "rapid heart rate",
      "cough"
    ]
  },
  {
    "disease": "prostate cancer",
    "specialists": [
      "Medical Oncologist",
      "Urologist",
      "Radiation Oncologist",
      "Radiologist",
      "Hematologist / Oncologist",
      "Radiation Oncology Medical Physicist",
      "Oncologist"
    ],
    "symptoms": [
      "retention of urine",
      "blood in urine",
      "symptoms of prostate",
      "frequent urination",
      "involuntary urination",
      "impotence",
      "excessive urination at night",
      "flushing",
      "symptoms of bladder",
      "pain during intercourse",
      "trouble urinating",
      "decreased force in the stream of urine",
      "blood in the urine",
      "blood in the semen",
      "bone pain",
      "losing weight without trying",
      "erectile dysfunction"
    ]
  },
  {
    "disease": "breast cancer",
    "specialists": [
      "Medical Oncologist",
      "General Surgeon",
      "Hematologist / Oncologist",
      "Oncologist",
      "Radiation Oncologist",
      "Radiation Oncology Medical Physicist",
      "Pathologist",
      "Internist",
      "Surgical Oncologist",
      "Radiologist",
      "Family Physician",
      "Hospice & Palliative Medicine Specialist",
      "Physiatrist",
      "Palliative Care Specialist"
    ],
    "symptoms": [
      "lump or mass of breast",
      "pain or soreness of breast",
      "hot flashes",
      "bleeding or discharge from nipple",
      "joint stiffness or tightness",
      "a breast lump or thickening that feels different from the surrounding tissue",
      "change in the size, shape or appearance of a breast",
      "changes to the skin over the breast, such as dimpling",
      "a newly inverted nipple",
      "peeling, scaling, crusting or flaking of the pigmented area of skin surrounding the nipple (areola) or breast skin",
      "redness or pitting of the skin over your breast, like the skin of an orange"
    ]
  },
  {
    "disease": "lung cancer",
    "specialists": [
      "Radiation Oncology Medical Physicist",
      "Oncologist",
      "Hematologist / Oncologist",
      "Radiation Oncologist",
      "Pulmonologist",
      "Radiologist",
      "Thoracic Surgeon",
      "Cardiothoracic Surgeon",
      "Pathologist",
      "Cardiovascular Surgeon"
    ],
    "symptoms": [
      "shortness of breath",
      "cough",
      "fatigue",
      "decreased appetite",
      "hemoptysis",
      "drainage in throat",
      "leg weakness",
      "smoking problems",
      "a new cough that doesn't go away",
      "coughing up blood, even a small amount",
      "chest pain",
      "hoarseness",
      "losing weight without trying",
      "bone pain",
      "headache"
    ]
  },
  {
    "disease": "colon cancer",
    "specialists": [
      "General Surgeon",
      "Colon and Rectal Surgeon",
      "Radiologist",
      "Radiation Oncologist",
      "Oncologist",
      "Gastroenterologist",
      "Hematologist / Oncologist",
      "Pathologist"
    ],
    "symptoms": [
      "a persistent change in your bowel habits, including diarrhea or constipation or a change in the consistency of your stool",
      "rectal bleeding or blood in your stool",
      "persistent abdominal discomfort, such as cramps, gas or pain",
      "a feeling that your bowel doesn't empty completely",
      "weakness or fatigue",
      "unexplained weight loss"
    ]
  },
  {
    "disease": "schizophrenia",
    "specialists": [
      "Psychiatrist",
      "Psychologist"
    ],
    "symptoms": [
      "hallucinations auditory",
      "hypersomnolence",
      "irritable mood",
      "verbal auditory hallucinations",
      "patient non compliance",
      "agitation",
      "suicidal",
      "worry",
      "hallucinations visual",
      "underweight",
      "homelessness",
      "depressive or psychotic symptoms",
      "delusions or hallucinations",
      "depression",
      "anxiety and nervousness",
      "hostile behavior",
      "fears and phobias",
      "drug abuse",
      "insomnia",
      "temper problems",
      "excessive anger",
      "hysterical behavior",
      "low self-esteem",
      "delusions - these are false beliefs that are not based in reality; for example, you think that you're being harmed or harassed; certain gestures or comments are directed at you; you have exceptional ability or fame; another person is in love with you; or a major catastrophe is about to occur; delusions occur in most people with schizophrenia",
      "hallucinations - these usually involve seeing or hearing things that don't exist; yet for the person with schizophrenia, they have the full force and impact of a normal experience; hallucinations can be in any of the senses, but hearing voices is the most common hallucination",
      "disorganized thinking (speech) - disorganized thinking is inferred from disorganized speech; effective communication can be impaired, and answers to questions may be partially or completely unrelated; rarely, speech may include putting together meaningless words that can't be understood, sometimes known as word salad",
      "extremely disorganized or abnormal motor behavior - this may show in a number of ways, from childlike silliness to unpredictable agitation; behavior isn't focused on a goal, so it's hard to do tasks; behavior can include resistance to instructions, inappropriate or bizarre posture, a complete lack of response, or useless and excessive movement",
      "negative symptoms - this refers to reduced or lack of ability to function normally; for example, the person may neglect personal hygiene or appear to lack emotion (doesn't make eye contact, doesn't change facial expressions or speaks in a monotone); also, the person may lose interest in everyday activities, socially withdraw or lack the ability to experience pleasure"
    ]
  },
  {
    "disease": "bipolar disorder",
    "specialists": [
      "Psychiatrist",
      "Psychologist"
    ],
    "symptoms": [
      "feeling suicidal",
      "energy increased",
      "suicidal",
      "irritable mood",
      "agitation",
      "has religious belief",
      "disturbed family",
      "hallucinations auditory",
      "verbal auditory hallucinations",
      "weepiness",
      "behavior hyperactive",
      "catatonia",
      "feeling hopeless",
      "worry",
      "sleeplessness",
      "hypersomnia",
      "difficulty",
      "hallucinations visual",
      "hyperhidrosis disorder",
      "mydriasis",
      "extrapyramidal sign",
      "loose associations",
      "intoxication",
      "motor retardation",
      "homelessness",
      "blackout",
      "tremor",
      "exhaustion",
      "depressive or psychotic symptoms",
      "depression",
      "anxiety and nervousness",
      "insomnia",
      "hostile behavior",
      "delusions or hallucinations",
      "abusing alcohol",
      "drug abuse",
      "excessive anger",
      "temper problems",
      "fears and phobias",
      "obsessions and compulsions",
      "bipolar i disorder - you've had at least one manic episode that may be preceded or followed by hypomanic or major depressive episodes; in some cases, mania may trigger a break from reality (psychosis)",
      "bipolar ii disorder - you've had at least one major depressive episode and at least one hypomanic episode, but you've never had a manic episode",
      "cyclothymic disorder - you've had at least two years - or one year in children and teenagers - of many periods of hypomania symptoms and periods of depressive symptoms (though less severe than major depression)",
      "other types - these include, for example, bipolar and related disorders induced by certain drugs or alcohol or due to a medical condition, such as cushing's disease, multiple sclerosis or stroke"
    ]
  },
  {
    "disease": "panic disorder",
    "specialists": [
      "Psychiatrist",
      "Psychologist"
    ],
    "symptoms": [
      "anxiety and nervousness",
      "depression",
      "shortness of breath",
      "depressive or psychotic symptoms",
      "sharp chest pain",
      "dizziness",
      "insomnia",
      "abnormal involuntary movements",
      "chest tightness",
      "palpitations",
      "irregular heartbeat",
      "breathing fast"
    ]
  },
  {
    "disease": "generalized anxiety disorder",
    "specialists": [
      "Psychiatrist",
      "Psychologist",
      "Family Physician",
      "Pediatrician"
    ],
    "symptoms": [
      "persistent worrying or anxiety about a number of areas that are out of proportion to the impact of the events",
      "overthinking plans and solutions to all possible worst-case outcomes",
      "perceiving situations and events as threatening, even when they aren't",
      "difficulty handling uncertainty",
      "indecisiveness and fear of making the wrong decision",
      "inability to set aside or let go of a worry",
      "inability to relax, feeling restless, and feeling keyed up or on edge",
      "difficulty concentrating, or the feeling that your mind \"goes blank\"",
      "fatigue",
      "trouble sleeping",
      "muscle tension or muscle aches",
      "trembling, feeling twitchy",
      "nervousness or being easily startled",
      "sweating",
      "nausea, diarrhea or irritable bowel syndrome",
      "irritability",
      "performance at school or sporting events",
      "family members' safety",
      "being on time (punctuality)",
      "earthquakes, nuclear war or other catastrophic events",
      "feel overly anxious to fit in",
      "be a perfectionist",
      "redo tasks because they aren't perfect the first time",
      "spend excessive time doing homework",
      "lack confidence",
      "strive for approval",
      "require a lot of reassurance about performance",
      "have frequent stomachaches or other physical complaints",
      "avoid going to school or avoid social situations",
      "you feel like you're worrying too much, and it's interfering with your work, relationships or other parts of your life",
      "you feel depressed or irritable, have trouble with drinking or drugs, or you have other mental health concerns along with anxiety",
      "you have suicidal thoughts or behaviors - seek emergency treatment immediately"
    ]
  },
  {
    "disease": "anxiety",
    "specialists": [
      "Psychiatrist",
      "Psychologist",
      "Pediatrician",
      "Family Physician"
    ],
    "symptoms": [
      "anxiety and nervousness",
      "depression",
      "sharp chest pain",
      "depressive or psychotic symptoms",
      "shortness of breath",
      "headache",
      "insomnia",
      "palpitations",
      "abnormal involuntary movements",
      "irregular heartbeat",
      "fears and phobias",
      "increased heart rate",
      "feeling nervous, restless or tense",
      "having a sense of impending danger, panic or doom",
      "having an increased heart rate",
      "breathing rapidly (hyperventilation)",
      "sweating",
      "trembling",
      "feeling weak or tired",
      "trouble concentrating or thinking about anything other than the present worry",
      "having trouble sleeping",
      "experiencing gastrointestinal (gi) problems",
      "having difficulty controlling worry",
      "having the urge to avoid things that trigger anxiety",
      "agoraphobia (ag-uh-ruh-foe-be-uh) is a type of anxiety disorder in which you fear and often avoid places or situations that might cause you to panic and make you feel trapped, helpless or embarrassed",
      "anxiety disorder due to a medical condition includes symptoms of intense anxiety or panic that are directly caused by a physical health problem",
      "generalized anxiety disorder includes persistent and excessive anxiety and worry about activities or events - even ordinary, routine issues; the worry is out of proportion to the actual circumstance, is difficult to control and affects how you feel physically; it often occurs along with other anxiety disorders or depression",
      "panic disorder involves repeated episodes of sudden feelings of intense anxiety and fear or terror that reach a peak within minutes (panic attacks); you may have feelings of impending doom, shortness of breath, chest pain, or a rapid, fluttering or pounding heart (heart palpitations); these panic attacks may lead to worrying about them happening again or avoiding situations in which they've occurred",
      "selective mutism is a consistent failure of children to speak in certain situations, such as school, even when they can speak in other situations, such as at home with close family members; this can interfere with school, work and social functioning",
      "separation anxiety disorder is a childhood disorder characterized by anxiety that's excessive for the child's developmental level and related to separation from parents or others who have parental roles",
      "social anxiety disorder (social phobia) involves high levels of anxiety, fear and avoidance of social situations due to feelings of embarrassment, self-consciousness and concern about being judged or viewed negatively by others",
      "specific phobias are characterized by major anxiety when you're exposed to a specific object or situation and a desire to avoid it; phobias provoke panic attacks in some people",
      "substance-induced anxiety disorder is characterized by symptoms of intense anxiety or panic that are a direct result of misusing drugs, taking medications, being exposed to a toxic substance or withdrawal from drugs;",
      "other specified anxiety disorder and unspecified anxiety disorder are terms for anxiety or phobias that don't meet the exact criteria for any other anxiety disorders but are significant enough to be distressing and disruptive"
    ]
  }
];

const ALL_SYMPTOMS = [
  "a breast lump or thickening that feels different from the surrounding tissue",
  "a burning sensation in your chest (heartburn), usually after eating, which might be worse at night",
  "a burning sensation when urinating",
  "a feeling that your bowel doesn't empty completely",
  "a new cough that doesn't go away",
  "a newly inverted nipple",
  "a persistent change in your bowel habits, including diarrhea or constipation or a change in the consistency of your stool",
  "a red rash that begins a few days after the pain",
  "a staring spell",
  "a strong, persistent urge to urinate",
  "abdominal bloating",
  "abdominal pain",
  "abdominal pain that feels worse after eating",
  "abdominal pain that radiates to your back",
  "abdominal pain, cramping or bloating that is related to passing a bowel movement",
  "abdominal tenderness",
  "abnormal appearing skin",
  "abnormal involuntary movements",
  "abnormal menstruation",
  "absence of menstruation",
  "abusing alcohol",
  "ache all over",
  "acidity",
  "acne or pimples",
  "active tuberculosis(tb) - also called tuberculosis(tb) disease, this condition makes you sick and, in most cases, can spread to others; it can occur weeks or years after infection with the tuberculosis(tb) bacteria",
  "adults older than age 65",
  "agitation",
  "agoraphobia (ag-uh-ruh-foe-be-uh) is a type of anxiety disorder in which you fear and often avoid places or situations that might cause you to panic and make you feel trapped, helpless or embarrassed",
  "allergic reaction",
  "allergy-induced asthma, triggered by airborne substances, such as pollen, mold spores, cockroach waste, or particles of skin and dried saliva shed by pets (pet dander)",
  "amnesia surrounding the traumatic event",
  "an enlarged thyroid gland (goiter), which may appear as a swelling at the base of your neck",
  "anemia, usually from iron deficiency",
  "angina pectoris",
  "ankle pain",
  "ankle swelling",
  "anxiety",
  "anxiety and nervousness",
  "anxiety disorder due to a medical condition includes symptoms of intense anxiety or panic that are directly caused by a physical health problem",
  "apyrexial",
  "arm pain",
  "arm weakness",
  "arthralgia",
  "ascites",
  "asthenia",
  "asthma signs and symptoms that are more frequent and bothersome",
  "aura",
  "avoid going to school or avoid social situations",
  "back cramps or spasms",
  "back pain",
  "be a perfectionist",
  "bedridden",
  "behavior hyperactive",
  "being on time (punctuality)",
  "bipolar i disorder - you've had at least one manic episode that may be preceded or followed by hypomanic or major depressive episodes; in some cases, mania may trigger a break from reality (psychosis)",
  "bipolar ii disorder - you've had at least one major depressive episode and at least one hypomanic episode, but you've never had a manic episode",
  "blackout",
  "bladder discomfort",
  "bleeding from your gums or nose",
  "bleeding or discharge from nipple",
  "bleeding under the skin, which might look like bruising",
  "blindness",
  "bloating and gas",
  "blood in sputum",
  "blood in stool",
  "blood in the semen",
  "blood in the urine",
  "blood in urine",
  "blood in your urine, stools or vomit",
  "blood vessels",
  "blurred and distorted vision",
  "blurred vision",
  "blurry vision",
  "bone marrow",
  "bone pain",
  "bone spurs - these extra bits of bone, which feel like hard lumps, can form around the affected joint",
  "bradycardia",
  "breath sounds decreased",
  "breathing fast",
  "breathing rapidly (hyperventilation)",
  "breathlessness",
  "brittle nails",
  "burning abdominal pain",
  "burning micturition",
  "butterfly-shaped rash on the face that covers the cheeks and bridge of the nose or rashes elsewhere on the body",
  "catatonia",
  "change in the size, shape or appearance of a breast",
  "changes in appearance of bowel movement",
  "changes in bowel patterns, especially more frequent bowel movements",
  "changes in how often you are having a bowel movement",
  "changes in menstrual patterns",
  "changes in stool appearance",
  "changes to the skin over the breast, such as dimpling",
  "chest discomfort",
  "chest pain",
  "chest pain when you breathe or cough",
  "chest pain, fast heartbeat or shortness of breath",
  "chest pain, or pain with breathing or coughing",
  "chest tightness",
  "chest tightness or pain",
  "children younger than age 2 with signs and symptoms",
  "chill",
  "chills",
  "chronic cough",
  "chronic fatigue syndrome",
  "cognitive difficulties - a symptom commonly referred to as \"fibro fog\" impairs the ability to focus, pay attention and concentrate on mental tasks",
  "cold hands and feet",
  "cold hands and feets",
  "concentration and memory complaints",
  "confusion or changes in mental awareness (in adults age 65 and older)",
  "confusion or feeling as if in a fog",
  "congestion in chest",
  "consciousness clear",
  "constipation",
  "constipation or diarrhea",
  "continuous feel of urine",
  "coryza",
  "cough",
  "cough, which may produce phlegm",
  "coughing for three or more weeks",
  "coughing or wheezing attacks that are worsened by a respiratory virus, such as a cold or the flu",
  "coughing up blood or mucus",
  "coughing up blood, even a small amount",
  "coughing up sputum",
  "cramps and spasms",
  "cyclothymic disorder - you've had at least two years - or one year in children and teenagers - of many periods of hypomania symptoms and periods of depressive symptoms (though less severe than major depression)",
  "dazed appearance",
  "decreased appetite",
  "decreased force in the stream of urine",
  "decreased heart rate",
  "decreased translucency",
  "delayed response to questions",
  "delusions - these are false beliefs that are not based in reality; for example, you think that you're being harmed or harassed; certain gestures or comments are directed at you; you have exceptional ability or fame; another person is in love with you; or a major catastrophe is about to occur; delusions occur in most people with schizophrenia",
  "delusions or hallucinations",
  "depression",
  "depressive or psychotic symptoms",
  "diarrhea",
  "diarrhoea",
  "diffculty speaking",
  "difficult or rapid breathing",
  "difficulty",
  "difficulty breathing",
  "difficulty concentrating, or the feeling that your mind \"goes blank\"",
  "difficulty handling uncertainty",
  "difficulty sleeping",
  "difficulty speaking",
  "difficulty swallowing",
  "diminished vision",
  "disorders of taste and smell",
  "disorganized thinking (speech) - disorganized thinking is inferred from disorganized speech; effective communication can be impaired, and answers to questions may be partially or completely unrelated; rarely, speech may include putting together meaningless words that can't be understood, sometimes known as word salad",
  "disrupted sleep",
  "distress respiratory",
  "disturbance of memory",
  "disturbance of smell or taste",
  "disturbed family",
  "dizziness",
  "dizziness or \"seeing stars\"",
  "dizziness or lightheadedness",
  "double vision",
  "drainage in throat",
  "drool",
  "drowsiness",
  "drug abuse",
  "dry eyes",
  "dry skin",
  "dry, cracked skin that may bleed or itch",
  "dyspnea",
  "dyspnea on exertion",
  "earthquakes, nuclear war or other catastrophic events",
  "ecchymosis",
  "elbow pain",
  "elbow swelling",
  "electric-shock sensations that occur with certain neck movements, especially bending the neck forward (lhermitte sign)",
  "elevated blood cholesterol level",
  "emphysematous change",
  "energy increased",
  "enlarged thyroid",
  "enlarged thyroid gland (goiter)",
  "erectile dysfunction",
  "erythema",
  "excessive anger",
  "excessive bleeding - you may experience occasional heavy menstrual periods or bleeding between periods (intermenstrual bleeding)",
  "excessive growth",
  "excessive hunger",
  "excessive urination at night",
  "exercise-induced asthma, which may be worse when the air is cold and dry",
  "exhaustion",
  "experiencing gastrointestinal (gi) problems",
  "extrapyramidal sign",
  "extreme fatigue",
  "extreme hunger",
  "extremely disorganized or abnormal motor behavior - this may show in a number of ways, from childlike silliness to unpredictable agitation; behavior isn't focused on a goal, so it's hard to do tasks; behavior can include resistance to instructions, inappropriate or bizarre posture, a complete lack of response, or useless and excessive movement",
  "eye moves abnormally",
  "eyes",
  "facial pain",
  "facial paresis",
  "fainting",
  "fall",
  "family members' safety",
  "fast heart rate",
  "fatigue",
  "fatigue - people with fibromyalgia often awaken tired, even though they report sleeping for long periods of time; sleep is often disrupted by pain, and many patients with fibromyalgia have other sleep disorders, such as restless legs syndrome and sleep apnea",
  "fatigue or drowsiness",
  "fatigue, fever and loss of appetite",
  "fatigue, muscle weakness",
  "fears and phobias",
  "feel overly anxious to fit in",
  "feeling cold",
  "feeling hopeless",
  "feeling nervous, restless or tense",
  "feeling suicidal",
  "feeling weak or tired",
  "fever",
  "fever, sweating and shaking chills",
  "fine, brittle hair",
  "fingers and toes that turn white or blue when exposed to cold or during stressful periods",
  "flat, circular rash anywhere on your body",
  "flatulence",
  "fluid-filled blisters that break open and crust over",
  "flushing",
  "focal weakness",
  "foot or toe pain",
  "foot or toe swelling",
  "forgetfulness, such as repeatedly asking the same question",
  "foul smell of urine",
  "frail",
  "frequent infections, such as gums or skin infections and vaginal infections",
  "frequent urination",
  "general feeling of discomfort",
  "generalized anxiety disorder includes persistent and excessive anxiety and worry about activities or events - even ordinary, routine issues; the worry is out of proportion to the actual circumstance, is difficult to control and affects how you feel physically; it often occurs along with other anxiety disorders or depression",
  "glossary",
  "grating sensation - you might feel a grating sensation when you use the joint, and you might hear popping or crackling",
  "green sputum",
  "groggy",
  "guaiac positive",
  "gurgle",
  "haemoptysis",
  "haemorrhage",
  "hallucinations - these usually involve seeing or hearing things that don't exist; yet for the person with schizophrenia, they have the full force and impact of a normal experience; hallucinations can be in any of the senses, but hearing voices is the most common hallucination",
  "hallucinations auditory",
  "hallucinations visual",
  "hand or finger pain",
  "hand or finger stiffness or tightness",
  "hand or finger swelling",
  "hand or finger weakness",
  "has religious belief",
  "have frequent stomachaches or other physical complaints",
  "having a sense of impending danger, panic or doom",
  "having an increased heart rate",
  "having difficulty controlling worry",
  "having the urge to avoid things that trigger anxiety",
  "having trouble sleeping",
  "headache",
  "headache - a sudden, severe headache, which may be accompanied by vomiting, dizziness or altered consciousness, may indicate that you're having a stroke",
  "headache, dizziness or lightheadedness",
  "headaches",
  "headaches and fatigue",
  "headaches, confusion and memory loss",
  "heart",
  "heartburn",
  "heavier than normal or irregular menstrual periods",
  "heavy menstrual flow",
  "heme positive",
  "hemiplegia",
  "hemoptysis",
  "high fever",
  "hip pain",
  "hoarseness",
  "homelessness",
  "hostile behavior",
  "hot flashes",
  "hot flush",
  "hurts to breath",
  "hyperhidrosis disorder",
  "hyperkalemia",
  "hypersomnia",
  "hypersomnolence",
  "hypokinesia",
  "hypometabolism",
  "hyponatremia",
  "hypotension",
  "hysterical behavior",
  "impaired memory",
  "impotence",
  "inability to relax, feeling restless, and feeling keyed up or on edge",
  "inability to set aside or let go of a worry",
  "increased appetite",
  "increased heart rate",
  "increased sensitivity to cold",
  "increased sensitivity to heat",
  "increased thirst",
  "increasing difficulty breathing, as measured with a device used to check how well your lungs are working (peak flow meter)",
  "indecisiveness and fear of making the wrong decision",
  "indigestion",
  "infertility",
  "infertility - sometimes, endometriosis is first diagnosed in those seeking treatment for infertility",
  "inflammation and redness - the affected joint or joints become swollen, tender, warm and red",
  "inflammation or soreness of your tongue",
  "inflammatory nails",
  "insomnia",
  "intense joint pain - gout usually affects the big toe, but it can occur in any joint; other commonly affected joints include the ankles, knees, elbows, wrists and fingers; the pain is likely to be most severe within the first four to 12 hours after it begins",
  "intermenstrual bleeding",
  "interstitial cystitis or painful bladder syndrome",
  "intoxication",
  "involuntary urination",
  "irregular appearing scalp",
  "irregular heartbeat",
  "irregular heartbeat (arrhythmia)",
  "irregular heartbeats",
  "irritability",
  "irritability and other personality changes",
  "irritability or restlessness",
  "irritable bowel syndrome",
  "irritable mood",
  "itchiness of eye",
  "itching",
  "itching of skin",
  "itching, burning or soreness",
  "itchy eyelid",
  "itchy scalp",
  "itchy, blistery skin rash (dermatitis herpetiformis)",
  "joint pain",
  "joint pain and swelling",
  "joint pain, stiffness and swelling",
  "joint stiffness or tightness",
  "joint stiffness that is usually worse in the mornings and after inactivity",
  "joint swelling",
  "kidneys",
  "knee lump or mass",
  "knee pain",
  "knee swelling",
  "knee weakness",
  "labored breathing",
  "lack confidence",
  "lack of growth",
  "laryngitis",
  "latent tuberculosis(tb) - you have a tuberculosis(tb) infection, but the bacteria in your body are inactive and cause no symptoms; latent tuberculosis(tb), also called inactive tuberculosis(tb) or tuberculosis(tb) infection, isn't contagious; latent tuberculosis(tb) can turn into active tuberculosis(tb), so treatment is important",
  "leg cramps or spasms",
  "leg lump or mass",
  "leg pain",
  "leg stiffness or tightness",
  "leg swelling",
  "leg weakness",
  "lethargy",
  "lightheadedness",
  "limited range of motion - as gout progresses, you may not be able to move your joints normally",
  "lingering discomfort - after the most severe pain subsides, some joint discomfort may last from a few days to a few weeks; later attacks are likely to last longer and affect more joints",
  "long menstrual periods",
  "loose associations",
  "losing weight without trying",
  "loss of appetite",
  "loss of bone density (osteoporosis) or softening of bone (osteomalacia)",
  "loss of consciousness or awareness",
  "loss of flexibility - you might not be able to move your joint through its full range of motion",
  "loss of sensation",
  "low back pain",
  "low self-esteem",
  "low-grade fever that may worsen as the illness progresses",
  "lower abdominal pain",
  "lower than normal body temperature (in adults older than age 65 and people with weak immune systems)",
  "lump or mass of breast",
  "lungs",
  "malaise",
  "mass of body structure",
  "melena",
  "memory loss and confusion",
  "mental status changes",
  "migraine and other types of headaches",
  "mild fever",
  "monoclonal",
  "mood depressed",
  "mood swings",
  "motor retardation",
  "mouth ulcers",
  "muscle aches",
  "muscle aches, tenderness and stiffness",
  "muscle or joint pain",
  "muscle pain",
  "muscle tension or muscle aches",
  "muscle twitch",
  "muscle weakness",
  "muscle, bone or joint pain",
  "mydriasis",
  "myoclonus",
  "nasal congestion",
  "nausea",
  "nausea and vomiting",
  "nausea, diarrhea or irritable bowel syndrome",
  "nausea, vomiting or diarrhea",
  "neck pain",
  "negative symptoms - this refers to reduced or lack of ability to function normally; for example, the person may neglect personal hygiene or appear to lack emotion (doesn't make eye contact, doesn't change facial expressions or speaks in a monotone); also, the person may lose interest in everyday activities, socially withdraw or lack the ability to experience pleasure",
  "nerve tissue",
  "nervous system injury, including numbness and tingling in the feet and hands, possible problems with balance, and cognitive impairment",
  "nervousness or being easily startled",
  "nervousness, anxiety and irritability",
  "new or worsening asthma",
  "night sweat",
  "night sweats",
  "nightmare",
  "non-productive cough",
  "nosebleed",
  "numbness",
  "numbness or weakness in one or more limbs that typically occurs on one side of your body at a time, or your legs and trunk",
  "obsessions and compulsions",
  "occupational asthma, triggered by workplace irritants such as chemical fumes, gases or dust",
  "oily, smelly stools (steatorrhea)",
  "or roughness",
  "orthopnea",
  "orthostasis",
  "other signs and symptoms - you may experience fatigue, diarrhea, constipation, bloating or nausea, especially during menstrual periods",
  "other specified anxiety disorder and unspecified anxiety disorder are terms for anxiety or phobias that don't meet the exact criteria for any other anxiety disorders but are significant enough to be distressing and disruptive",
  "other types - these include, for example, bipolar and related disorders induced by certain drugs or alcohol or due to a medical condition, such as cushing's disease, multiple sclerosis or stroke",
  "overthinking plans and solutions to all possible worst-case outcomes",
  "pain",
  "pain - affected joints might hurt during or after movement",
  "pain abdominal",
  "pain back",
  "pain behind the eyes",
  "pain chest",
  "pain during intercourse",
  "pain during pregnancy",
  "pain in eye",
  "pain of the anus",
  "pain or soreness of breast",
  "pain that worsens if you cough, walk or make other jarring movements",
  "pain with bowel movements or urination - you're most likely to experience these symptoms during a menstrual period",
  "pain with intercourse - pain during or after sex is common with endometriosis",
  "pain, burning, numbness or tingling",
  "pain, stiffness or swelling in your joints",
  "painful menstruation",
  "painful periods (dysmenorrhea) - pelvic pain and cramping may begin before and extend several days into a menstrual period; you may also have lower back and abdominal pain",
  "painful urination",
  "pale or yellowish skin",
  "pale skin",
  "pallor",
  "palpitation",
  "palpitations",
  "panic disorder involves repeated episodes of sudden feelings of intense anxiety and fear or terror that reach a peak within minutes (panic attacks); you may have feelings of impending doom, shortness of breath, chest pain, or a rapid, fluttering or pounding heart (heart palpitations); these panic attacks may lead to worrying about them happening again or avoiding situations in which they've occurred",
  "paralysis or numbness of the face, arm or leg - you may develop sudden numbness, weakness or paralysis in the face, arm or leg; this often affects just one side of the body; try to raise both your arms over your head at the same time; if one arm begins to fall, you may be having a stroke; also, one side of your mouth may droop when you try to smile",
  "paresthesia",
  "partial or complete loss of vision, usually in one eye at a time, often with pain during eye movement",
  "passing frequent, small amounts of urine",
  "patient non compliance",
  "peeling",
  "peeling, scaling, crusting or flaking of the pigmented area of skin surrounding the nipple (areola) or breast skin",
  "pelvic pain",
  "pelvic pain, in women - especially in the center of the pelvis and around the area of the pubic bone",
  "people receiving chemotherapy or taking medication that suppresses the immune system",
  "people with an underlying health condition or weakened immune system",
  "perceiving situations and events as threatening, even when they aren't",
  "performance at school or sporting events",
  "peripheral edema",
  "persistent abdominal discomfort, such as cramps, gas or pain",
  "persistent vomiting",
  "persistent worrying or anxiety about a number of areas that are out of proportion to the impact of the events",
  "phlegm",
  "pin-point pupils",
  "pleuritic pain",
  "polydypsia",
  "polyuria",
  "poor appetite, especially in infants and children with iron deficiency anemia",
  "poor circulation",
  "poor judgement",
  "postural tachycardia syndrome",
  "pounding of your heart (palpitations)",
  "presence of ketones in the urine (ketones are a byproduct of the breakdown of muscle and fat that happens when there's not enough available insulin)",
  "presence of q wave",
  "pressure chest",
  "problems seeing in one or both eyes - you may suddenly have blurred or blackened vision in one or both eyes, or you may see double",
  "problems with movement",
  "problems with sexual, bowel and bladder function",
  "productive cough",
  "prolonged double vision",
  "prostatism",
  "psychological adjustment problems and depression",
  "psychological symptoms such as fear, anxiety or deja vu",
  "puffy face",
  "puffy face and eyes",
  "rale",
  "rapid breathing",
  "rapid heart rate",
  "rapid heartbeat (tachycardia) - commonly more than 100 beats a minute",
  "rapid pulse",
  "rash",
  "recent pregnancy",
  "rectal bleeding",
  "rectal bleeding or blood in your stool",
  "red patches of skin covered with thick, silvery scales",
  "redness",
  "redness or pitting of the skin over your breast, like the skin of an orange",
  "redo tasks because they aren't perfect the first time",
  "reduced ability to exercise",
  "reduced functioning of the spleen (hyposplenism)",
  "regurgitation",
  "regurgitation of food or sour liquid",
  "repeating questions",
  "require a lot of reassurance about performance",
  "restlessness",
  "retention of urine",
  "rhonchus",
  "rib pain",
  "rigor - temperature-associated observation",
  "ringing in the ears",
  "rusty sputum",
  "salivary glands",
  "scaliness",
  "seizure",
  "seizures",
  "selective mutism is a consistent failure of children to speak in certain situations, such as school, even when they can speak in other situations, such as at home with close family members; this can interfere with school, work and social functioning",
  "sensation of a lump in your throat",
  "sensations of a fast, fluttering or pounding heartbeat (palpitations)",
  "sensitivity to light",
  "sensitivity to light and noise",
  "sensitivity to touch",
  "separation anxiety disorder is a childhood disorder characterized by anxiety that's excessive for the child's developmental level and related to separation from parents or others who have parental roles",
  "severe stomach pain",
  "sharp abdominal pain",
  "sharp chest pain",
  "shortness of breath",
  "shoulder cramps or spasms",
  "shoulder pain",
  "side pain",
  "silver like dusting",
  "skin",
  "skin dryness",
  "skin growth",
  "skin lesion",
  "skin lesions that appear or worsen with sun exposure",
  "skin moles",
  "skin peeling",
  "skin rash",
  "skin swelling",
  "skin thinning",
  "sleep disturbances",
  "sleepiness",
  "sleeplessness",
  "sleepy",
  "slow-healing sores",
  "slowed heart rate",
  "slurred speech",
  "slurring words",
  "small dents in nails",
  "small scaling spots (commonly seen in children)",
  "smoking problems",
  "social anxiety disorder (social phobia) involves high levels of anxiety, fear and avoidance of social situations due to feelings of embarrassment, self-consciousness and concern about being judged or viewed negatively by others",
  "sore throat",
  "sore to touch",
  "specific phobias are characterized by major anxiety when you're exposed to a specific object or situation and a desire to avoid it; phobias provoke panic attacks in some people",
  "speech slurred",
  "spend excessive time doing homework",
  "spots or clouds in vision",
  "st segment depression",
  "st segment elevation",
  "stiff muscles",
  "stiff neck",
  "stiffness - joint stiffness might be most noticeable upon awakening or after being inactive",
  "stiffness all over",
  "stomach bloating",
  "stomach pain",
  "stool color yellow",
  "strive for approval",
  "strong-smelling urine",
  "substance-induced anxiety disorder is characterized by symptoms of intense anxiety or panic that are a direct result of misusing drugs, taking medications, being exposed to a toxic substance or withdrawal from drugs;",
  "sudden pain that begins around your navel and often shifts to your lower right abdomen",
  "sudden pain that begins on the right side of the lower abdomen",
  "suicidal",
  "suprapubic pain",
  "sweat",
  "sweating",
  "sweating increased",
  "swelled lymph nodes",
  "swelling",
  "swelling - this might be caused by soft tissue inflammation around the joint",
  "swollen and stiff joints",
  "swollen extremeties",
  "swollen glands",
  "symptom aggravating factors",
  "symptoms of bladder",
  "symptoms of prostate",
  "symptoms of the face",
  "symptoms of the kidneys",
  "syncope",
  "t wave inverted",
  "tachypnea",
  "temper problems",
  "temporary confusion",
  "temporary loss of consciousness (though this doesn't always occur)",
  "temporomandibular joint disorders",
  "tender, warm, swollen joints",
  "tenderness - your joint might feel tender when you apply light pressure to or near it",
  "tenderness when touching the abdomen",
  "the need to use a quick-relief inhaler more often",
  "thickened, pitted or ridged nails",
  "thinning hair",
  "thirst",
  "tingling or numbness - you may notice tingling and numbness in the fingers or hand; usually the thumb and index, middle or ring fingers are affected, but not the little finger; you might feel a sensation like an electric shock in these fingersthe sensation may travel from the wrist up the arm; these symptoms often occur while holding a steering wheel, phone or newspaper, or may wake you from sleepmany people \"shake out\" their hands to try to relieve their symptoms; the numb feeling may become constant over time",
  "tingling or pain in parts of your body",
  "tired",
  "too little hair",
  "transaminitis",
  "trembling",
  "trembling, feeling twitchy",
  "tremor",
  "tremor - usually a fine trembling in your hands and fingers",
  "tremor resting",
  "tremor, lack of coordination or unsteady gait",
  "trouble concentrating or thinking about anything other than the present worry",
  "trouble sleeping",
  "trouble sleeping caused by shortness of breath, coughing or wheezing",
  "trouble speaking and understanding what others are saying - you may experience confusion, slur words or have difficulty understanding speech",
  "trouble urinating",
  "trouble walking - you may stumble or lose your balance; you may also have sudden dizziness or a loss of coordination",
  "tumor cell invasion",
  "ulcers on tongue",
  "unable to concentrate",
  "unconscious state",
  "uncontrollable jerking movements of the arms and legs",
  "underweight",
  "unexplained weight loss",
  "unintentional weight loss",
  "unintentional weight loss, even when your appetite and food intake stay the same or increase",
  "unpredictable menstruation",
  "unresponsiveness",
  "unsteady gait",
  "unusual cravings for non-nutritive substances, such as ice, dirt or starch",
  "upper abdominal pain",
  "urine that appears cloudy",
  "urine that appears red, bright pink or cola-colored - a sign of blood in the urine",
  "vaginal itching",
  "vaginal pain",
  "verbal auditory hallucinations",
  "vertigo",
  "visual disturbances",
  "vomiting",
  "vomiting blood",
  "vulvar sore",
  "weakness",
  "weakness - you may experience weakness in the hand and drop objects; this may be due to the numbness in the hand or weakness of the thumb's pinching muscles, which are also controlled by the median nerve",
  "weakness or fatigue",
  "weepiness",
  "weight gain",
  "weight loss",
  "wheelchair bound",
  "wheezing",
  "wheezing when exhaling, which is a common sign of asthma in children",
  "widespread pain - the pain associated with fibromyalgia often is described as a constant dull ache that has lasted for at least three months; to be considered widespread, the pain must occur on both sides of your body and above and below your waist",
  "worry",
  "wrist pain",
  "wrist swelling",
  "wrist weakness",
  "yellow sputum",
  "yellowing of eyes",
  "you feel depressed or irritable, have trouble with drinking or drugs, or you have other mental health concerns along with anxiety",
  "you feel like you're worrying too much, and it's interfering with your work, relationships or other parts of your life",
  "you have suicidal thoughts or behaviors - seek emergency treatment immediately"
];
